/**
 * The SQL rewrite brick: both statements on screen with no interaction, and the injected tenant
 * scoping marked inside the one that ran.
 */

import { cleanup, render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";

import { SqlRewrite } from "./SqlRewrite";

afterEach(() => {
  cleanup();
  vi.unstubAllGlobals();
});

const GENERATED = "SELECT department, AVG(salary) AS avg FROM employees GROUP BY department";
const EXECUTED =
  "SELECT department, AVG(salary) AS avg FROM (SELECT * FROM employees " +
  "WHERE employees.tenant_id = ?) AS employees GROUP BY department";

function marks(container: HTMLElement, selector: string): string[] {
  return [...container.querySelectorAll(selector)].map((mark) => mark.textContent ?? "");
}

function bodies(container: HTMLElement): string[] {
  return [...container.querySelectorAll(".code-block-body")].map((body) => body.textContent ?? "");
}

describe("the pair, unconditionally", () => {
  it("shows both statements whole with no interaction", () => {
    const { container } = render(<SqlRewrite generated={GENERATED} executed={EXECUTED} />);

    expect(screen.getByText("generated by the model")).toBeTruthy();
    expect(screen.getByText("executed after tenant scoping")).toBeTruthy();
    expect(bodies(container)).toEqual([GENERATED, EXECUTED]);
  });

  it("puts the executed card second, so what ran sits nearest the result once they stack", () => {
    const { container } = render(<SqlRewrite generated={GENERATED} executed={EXECUTED} />);
    const labels = [...container.querySelectorAll(".code-block-label")].map((el) => el.textContent);

    expect(labels).toEqual(["generated by the model", "executed after tenant scoping"]);
  });

  it("offers no toggle at all", () => {
    render(<SqlRewrite generated={GENERATED} executed={EXECUTED} />);

    expect(screen.queryByRole("button", { name: /show/ })).toBeNull();
  });

  it("gives each card its own copy control, writing plain SQL rather than the markup", () => {
    vi.stubGlobal("navigator", { clipboard: { writeText: vi.fn() } });
    render(<SqlRewrite generated={GENERATED} executed={EXECUTED} />);

    expect(screen.getAllByRole("button", { name: "copy" })).toHaveLength(2);
  });
});

describe("the highlight inside the executed card", () => {
  it("marks only what the scoping layer added, tenant predicate and bound parameter", () => {
    const { container } = render(<SqlRewrite generated={GENERATED} executed={EXECUTED} />);
    const executed = container.querySelectorAll(".code-block-body")[1] as HTMLElement;

    expect(marks(executed, ".sql-add")).toEqual([
      "(SELECT * FROM employees WHERE employees.tenant_id = ?) AS employees",
    ]);
    expect(executed.textContent).toBe(EXECUTED);
  });

  it("leaves the generated card unmarked - it is model output, rendered as text", () => {
    const { container } = render(<SqlRewrite generated={GENERATED} executed={EXECUTED} />);
    const generated = container.querySelectorAll(".code-block-body")[0] as HTMLElement;

    expect(generated.querySelector(".sql-add")).toBeNull();
    expect(generated.textContent).toBe(GENERATED);
  });

  it("leaves the model's own words unmarked", () => {
    const { container } = render(<SqlRewrite generated={GENERATED} executed={EXECUTED} />);
    const marked = marks(container, ".code-block-body .sql-add").join(" ");

    expect(marked).not.toContain("AVG");
    expect(marked).not.toContain("GROUP BY");
  });

  it("says what the highlight means, because a colour alone claims nothing", () => {
    render(<SqlRewrite generated={GENERATED} executed={EXECUTED} />);

    expect(screen.getByText(/added by the RLS rewrite/)).toBeTruthy();
  });

  it("still shows the pair, unmarked, for a statement too long to align", () => {
    const long = `SELECT ${Array.from({ length: 300 }, (_, index) => `c${index}`).join(", ")} FROM employees`;
    const { container } = render(<SqlRewrite generated={long} executed={long} />);

    expect(bodies(container)).toEqual([long, long]);
    expect(container.querySelector(".sql-add")).toBeNull();
    expect(container.querySelector(".sql-legend")).toBeNull();
  });
});
