/**
 * SqlRewrite — what the model wrote and what actually ran, both on screen, with the tenant
 * scoping highlighted inside the statement that ran. `SqlTemplate` is the same card for a
 * statement with no generated side: a fixed template the server composed, its scoping marked the
 * same way, so both trace cards speak one visual language.
 *
 * This is the demo's money shot, and it has to carry two readings at once. The pair is the
 * before and after of the security boundary; the highlight inside the right card points at the
 * exact text `db.execute_scoped` wrapped around every `employees` reference (ADR 0002 layer 3).
 * An earlier version showed the executed statement alone with the marking inside it and put the
 * pair one click behind a `show both` toggle, which made the reader choose one of the two
 * readings and hid the other behind an interaction nobody performs mid-demo. Both are now
 * unconditional (issue #121).
 *
 * `lib/sqldiff.ts` owns the alignment and the template's pattern match; this brick only paints
 * them, through one `Mark` and one `Legend`, so neither card can drift from the other. A statement
 * too long to align renders as the plain pair, and a template without the scoping pattern renders
 * unmarked — the highlight is the bonus, the statement is the floor. The copy control on any card
 * always writes plain SQL, never the markup.
 *
 * Pattern from beautifului.dev (MIT): its diff surfaces mark an edit in place rather than
 * beside it. Reimplemented, not copied - its own diffs are line-granular with a +/- gutter,
 * which cannot show this rewrite, since sqlglot re-renders the statement onto one line and the
 * whole change is inside it.
 */

import { useMemo } from "react";

import { CodeBlock } from "./CodeBlock";
import { diffSql, markScoping } from "../lib/sqldiff";
import type { DiffSegment } from "../lib/sqldiff";

const GENERATED_LABEL = "generated by the model";
const EXECUTED_LABEL = "executed after tenant scoping";
const TEMPLATE_LABEL = "executed SQL (tenant-scoped template)";
const LEGEND = "added by the RLS rewrite - the tenant filter, bound as a parameter";

export function SqlRewrite({ generated, executed }: { generated: string; executed: string }) {
  const segments = useMemo(() => diffSql(generated, executed), [generated, executed]);

  return (
    <div className="sql-rewrite">
      <div className="sql-pair">
        <CodeBlock label={GENERATED_LABEL} code={generated} />
        <CodeBlock label={EXECUTED_LABEL} code={executed} tone="accent">
          {segments?.map((segment, index) => (
            <Mark key={index} segment={segment} />
          ))}
        </CodeBlock>
      </div>
      {segments ? <Legend /> : null}
    </div>
  );
}

/**
 * The executed statement of a fixed-template tool: SQL the server composed from allowlisted
 * arguments and never the model's own words, marked and legended exactly like the pair's
 * executed card, since the same layer scoped it.
 */
export function SqlTemplate({ sql }: { sql: string }) {
  const segments = useMemo(() => markScoping(sql), [sql]);

  return (
    <div className="sql-rewrite">
      <CodeBlock label={TEMPLATE_LABEL} code={sql} tone="accent">
        {segments?.map((segment, index) => (
          <Mark key={index} segment={segment} />
        ))}
      </CodeBlock>
      {segments ? <Legend /> : null}
    </div>
  );
}

/** What the highlight means, stated once for every card that carries one. */
function Legend() {
  return (
    <p className="sql-legend">
      <mark className="sql-add">{LEGEND}</mark>
    </p>
  );
}

/** One run of the statement that ran: the model's own words, or what the rewrite inserted. */
function Mark({ segment }: { segment: DiffSegment }) {
  if (segment.kind === "add") return <mark className="sql-add">{segment.text}</mark>;
  return <>{segment.text}</>;
}
