/**
 * SqlRewrite — the generated-versus-executed pair, as one statement with the tenant scoping
 * marked inside it.
 *
 * This is the demo's money shot, so it is rendered as the thing it actually is: the executed
 * statement IS the model's statement plus what `db.execute_scoped` wrapped around every
 * `employees` reference (ADR 0002 layer 3). Marking that inside one statement puts the tenant
 * predicate and the bound parameter in the reader's eye in one glance, where two cards left
 * them to spot the difference by eye across a gap. `lib/sqldiff.ts` owns the alignment; this
 * brick only paints it.
 *
 * The two cards are one click away and are what a statement too long to align falls back to,
 * because they are still the better read for lifting either statement out whole - and the copy
 * control always writes plain SQL, never the markup.
 *
 * Pattern from beautifului.dev (MIT): its diff surfaces mark an edit in place rather than
 * beside it. Reimplemented, not copied - its own diffs are line-granular with a +/- gutter,
 * which cannot show this rewrite, since sqlglot re-renders the statement onto one line and the
 * whole change is inside it.
 */

import { useMemo, useState } from "react";

import { Button } from "./Button";
import { CodeBlock } from "./CodeBlock";
import { diffSql } from "../lib/sqldiff";
import type { DiffSegment } from "../lib/sqldiff";

const GENERATED_LABEL = "generated by the model";
const EXECUTED_LABEL = "executed after tenant scoping";
const LEGEND = "added by the RLS rewrite - the tenant filter, bound as a parameter";
const REMOVED_LEGEND = "replaced";
const TO_PAIR = "show both";
const TO_DIFF = "show the diff";

export function SqlRewrite({ generated, executed }: { generated: string; executed: string }) {
  const segments = useMemo(() => diffSql(generated, executed), [generated, executed]);
  const [pair, setPair] = useState(false);
  const removed = segments?.some((segment) => segment.kind === "del") ?? false;

  if (segments === null || pair) {
    return (
      <div className="sql-pair">
        <CodeBlock label={GENERATED_LABEL} code={generated} />
        <CodeBlock
          label={EXECUTED_LABEL}
          code={executed}
          tone="accent"
          actions={
            segments === null ? undefined : (
              <Button className="btn-xs" onClick={() => setPair(false)}>
                {TO_DIFF}
              </Button>
            )
          }
        />
      </div>
    );
  }

  return (
    <div className="sql-rewrite">
      <CodeBlock
        label={EXECUTED_LABEL}
        code={executed}
        tone="accent"
        actions={
          <Button className="btn-xs" onClick={() => setPair(true)}>
            {TO_PAIR}
          </Button>
        }
      >
        {segments.map((segment, index) => (
          <Mark key={index} segment={segment} />
        ))}
      </CodeBlock>
      <p className="sql-legend">
        <mark className="sql-add">{LEGEND}</mark>
        {removed ? <del className="sql-del">{REMOVED_LEGEND}</del> : null}
      </p>
    </div>
  );
}

/** One run of the statement: kept as the model wrote it, added by the rewrite, or replaced by it. */
function Mark({ segment }: { segment: DiffSegment }) {
  if (segment.kind === "add") return <mark className="sql-add">{segment.text}</mark>;
  if (segment.kind === "del") return <del className="sql-del">{segment.text}</del>;
  return <>{segment.text}</>;
}
