/**
 * ToolResultView — the body of a `tool_result` step: whatever the tool's `data` payload
 * carries, each key through the brick that owns it.
 *
 * The generated and the executed statement sit side by side (KB's two-column
 * `.usage-grid`, one `CodeBlock` per cell): that pair is the layer-3 rewrite made
 * visible - the model wrote the left column, the scoped executor ran the right one with
 * the tenant bound into it (ADR 0012). Rows go through `DataTable`, a chart through the
 * `Chart` brick verbatim, retrieved notes through note cards, and a payload with no
 * structured keys falls back to the text the model itself read, so no result is ever
 * shown as nothing.
 */

import { Chart } from "../charts";
import { DataTable } from "../DataTable";
import { CodeBlock } from "../CodeBlock";
import type { NoteMatch, ToolResultData } from "../../lib/sse";

const GENERATED_LABEL = "generated by the model";
const EXECUTED_LABEL = "executed after tenant scoping";
const EXECUTED_ONLY_LABEL = "executed SQL (tenant-scoped template)";

export function ToolResultView({ content, data }: { content: string; data: ToolResultData }) {
  const anomalyColumns = data.anomalies?.length ? Object.keys(data.anomalies[0]) : [];
  const structured =
    Boolean(data.executed_sql) ||
    Boolean(data.columns) ||
    Boolean(data.chart_spec) ||
    Boolean(data.anomalies) ||
    Boolean(data.notes);

  return (
    <>
      {data.generated_sql && data.executed_sql ? (
        <div className="sql-pair">
          <CodeBlock label={GENERATED_LABEL} code={data.generated_sql} />
          <CodeBlock label={EXECUTED_LABEL} code={data.executed_sql} tone="accent" />
        </div>
      ) : data.executed_sql ? (
        <CodeBlock label={EXECUTED_ONLY_LABEL} code={data.executed_sql} tone="accent" />
      ) : null}

      {data.columns && data.rows ? <DataTable columns={data.columns} rows={data.rows} /> : null}

      {data.chart_spec ? <Chart spec={data.chart_spec} /> : null}

      {data.anomalies ? (
        <DataTable
          columns={anomalyColumns}
          rows={data.anomalies.map((anomaly) => anomalyColumns.map((column) => anomaly[column]))}
          empty="No outliers beyond the Tukey fences."
        />
      ) : null}

      {data.notes ? <NoteList notes={data.notes} /> : null}

      {structured ? null : <pre className="trace-text">{content}</pre>}
    </>
  );
}

/** Retrieved notes are employee-written text: shown as quoted data, never as instructions. */
function NoteList({ notes }: { notes: NoteMatch[] }) {
  if (notes.length === 0) return <p className="data-table-note">No notes matched.</p>;
  return (
    <ul className="note-list">
      {notes.map((note) => (
        <li className="note-card" key={`${note.user_id}-${note.distance}`}>
          <div className="note-head">
            <span className="note-name">{note.name}</span>
            <span className="note-meta">
              #{note.user_id} · distance {note.distance.toFixed(3)}
            </span>
          </div>
          <p className="note-text">{note.note}</p>
        </li>
      ))}
    </ul>
  );
}
